### ISSUE TITLE
Password cracking

### ISSUE THREAD

**Issue by stewrav** [stewrav/py1#25]
My password is hashed using the MD5 algorithm.  The checksum is e358efa489f58062f10dd7316b65649e.  Can you find my password?

**Comment by puden** [comment]
password is t

**Comment by stewrav** [comment]
Nice.  Next hash is afb0fced528eaac5fe170b763cda5975.

**Comment by stewrav** [comment]
Password was S8.  Excellent!

Next hash is _e2cc35d756ad1652e5ecd1b3417ef564_.  The password is obviously at least one character and I'll help you out and say that it's less than twenty characters.

**Comment by stewrav** [comment]
I wrote my password cracking program and I realized that the above hash is too difficult with the computers we have.  Try db6c0caafd2c276603e0252dcfed61db instead.  It's less than 10 characters.
